name: Linter
on:
    push:
        branches: main
    pull_request:
        branches: main

    jobs:
        lint:
            runs-on: ubuntu-latest
            steps:
                - uses: action/checkout@4
                - uses: actions/setup-node@v4
                  with:
                      node-version: 'lts/*'
                - name: install dependencies
                  run: npm ci
                - name: Run ESLint (fix) and Prettier
                  run: |
                      npm run lint:fix
                      npm run prettier:write
